### ISSUE TITLE
Can't install via omf

### ISSUE THREAD

**Issue by Worie** [wfscheper/plugin-docker#1]
when running `omf install docker` i get: 

```
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package docker
fatal: repository 'docker' does not exist
Could not install docker.
```

is the name in the readme valid?

**Comment by dotCipher** [comment]
Same issue here, any updates on this?  I don't see it included in https://github.com/oh-my-fish/packages-main/tree/master/packages

**Comment by wfscheper** [comment]
Hey guys,

Thanks for your interest in this, but this plugin is not part of OMF. See oh-my-fish/oh-my-fish#448.
